// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/chat.ts";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/image.tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Chat.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/chat.ts": $2,
    "./routes/api/joke.ts": $3,
    "./routes/image.tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Chat.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
